### ISSUE TITLE
Support PBS (Proxmox backup server)

### ISSUE THREAD

**Issue by Luckyvb** [Weilbyte/PVEDiscordDark#63]
It`s wil be cool if script support PBS ^)

**Comment by Weilbyte** [comment]
Duplicate of #44. No current plans to support PBS.

**Comment by Luckyvb** [comment]
Alfa
Fork https://github.com/Luckyvb/PVEDiscordDark
new file:   PBSDiscordDark.sh
new file:   PVEDiscordDark/js/PBSDiscordDark.js
new file:   PVEDiscordDark/sass/PBSDiscordDark.css

Looks not bad:
![изображение](https://user-images.githubusercontent.com/5268904/119281405-4c5ba200-bc3e-11eb-8382-9b2dccb3991e.png)

**Comment by eins** [comment]
Hello @Luckyvb thanks for the PBSDiscordDark script.
I noticed that your fork doesn't have an Issue option to report issues. 
I got  message because the pbs version 2.1.2 is to new for the script but the dark mode was installed.

@Weilbyte is there any chance to merge the changes so your current project will support proxmox backup ?
